<?php
/**
 * MessageApi
 * PHP version 7.3
 *
 * @category Class
 * @package  LanXinPlusOpenAPI
 * @author   LanXin OPEN
 * @link     https://openapi.lanxin.cn
 */

/**
 * LanXin+ OpenAPI
 *
 * LanXin+ OpenAPI Platform
 *
 * Generated by: https://openapi.lanxin.cn
 */

/**
 * NOTE: This class is auto generated by LanXin+(https://openapi.lanxin.cn).
 * https://openapi.lanxin.cn
 * Do not edit the class manually.
 */

namespace LanXinPlusOpenAPI\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use LanXinPlusOpenAPI\ApiException;
use LanXinPlusOpenAPI\Configuration;
use LanXinPlusOpenAPI\HeaderSelector;
use LanXinPlusOpenAPI\ObjectSerializer;

/**
 * MessageApi Class Doc Comment
 *
 * @category Class
 * @package  LanXinPlusOpenAPI
 * @author   LanXin OPEN
 * @link     https://openapi.lanxin.cn
 */
class MessageApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v1ChatNotificationFetch
     *
     * 获取通知消息会话状态
     *
     * @param  string $app_token app_token (required)
     * @param  string $userid userid (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \LanXinPlusOpenAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \LanXinPlusOpenAPI\Model\V1ChatNotificationFetchResponse
     */
    public function v1ChatNotificationFetch($app_token, $userid, $user_token = null)
    {
        list($response) = $this->v1ChatNotificationFetchWithHttpInfo($app_token, $userid, $user_token);
        return $response;
    }

    /**
     * Operation v1ChatNotificationFetchWithHttpInfo
     *
     * 获取通知消息会话状态
     *
     * @param  string $app_token app_token (required)
     * @param  string $userid userid (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \LanXinPlusOpenAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \LanXinPlusOpenAPI\Model\V1ChatNotificationFetchResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1ChatNotificationFetchWithHttpInfo($app_token, $userid, $user_token = null)
    {
        $request = $this->v1ChatNotificationFetchRequest($app_token, $userid, $user_token);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\LanXinPlusOpenAPI\Model\V1ChatNotificationFetchResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LanXinPlusOpenAPI\Model\V1ChatNotificationFetchResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\LanXinPlusOpenAPI\Model\V1ChatNotificationFetchResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LanXinPlusOpenAPI\Model\V1ChatNotificationFetchResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1ChatNotificationFetchAsync
     *
     * 获取通知消息会话状态
     *
     * @param  string $app_token app_token (required)
     * @param  string $userid userid (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1ChatNotificationFetchAsync($app_token, $userid, $user_token = null)
    {
        return $this->v1ChatNotificationFetchAsyncWithHttpInfo($app_token, $userid, $user_token)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1ChatNotificationFetchAsyncWithHttpInfo
     *
     * 获取通知消息会话状态
     *
     * @param  string $app_token app_token (required)
     * @param  string $userid userid (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1ChatNotificationFetchAsyncWithHttpInfo($app_token, $userid, $user_token = null)
    {
        $returnType = '\LanXinPlusOpenAPI\Model\V1ChatNotificationFetchResponse';
        $request = $this->v1ChatNotificationFetchRequest($app_token, $userid, $user_token);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1ChatNotificationFetch'
     *
     * @param  string $app_token app_token (required)
     * @param  string $userid userid (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1ChatNotificationFetchRequest($app_token, $userid, $user_token = null)
    {
        // verify the required parameter 'app_token' is set
        if ($app_token === null || (is_array($app_token) && count($app_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app_token when calling v1ChatNotificationFetch'
            );
        }
        // verify the required parameter 'userid' is set
        if ($userid === null || (is_array($userid) && count($userid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $userid when calling v1ChatNotificationFetch'
            );
        }

        $resourcePath = '/v1/chat/notification/{userid}/fetch';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($app_token !== null) {
            if('form' === 'form' && is_array($app_token)) {
                foreach($app_token as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['app_token'] = $app_token;
            }
        }
        // query params
        if ($user_token !== null) {
            if('form' === 'form' && is_array($user_token)) {
                foreach($user_token as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['user_token'] = $user_token;
            }
        }


        // path params
        if ($userid !== null) {
            $resourcePath = str_replace(
                '{' . 'userid' . '}',
                ObjectSerializer::toPathValue($userid),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1MessagesCreate
     *
     * 发送应用消息应用号通道
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V1MessagesCreateRequestBody $v1_messages_create_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \LanXinPlusOpenAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \LanXinPlusOpenAPI\Model\V1MessagesCreateResponse
     */
    public function v1MessagesCreate($app_token, $v1_messages_create_request_body, $user_token = null)
    {
        list($response) = $this->v1MessagesCreateWithHttpInfo($app_token, $v1_messages_create_request_body, $user_token);
        return $response;
    }

    /**
     * Operation v1MessagesCreateWithHttpInfo
     *
     * 发送应用消息应用号通道
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V1MessagesCreateRequestBody $v1_messages_create_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \LanXinPlusOpenAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \LanXinPlusOpenAPI\Model\V1MessagesCreateResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1MessagesCreateWithHttpInfo($app_token, $v1_messages_create_request_body, $user_token = null)
    {
        $request = $this->v1MessagesCreateRequest($app_token, $v1_messages_create_request_body, $user_token);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\LanXinPlusOpenAPI\Model\V1MessagesCreateResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LanXinPlusOpenAPI\Model\V1MessagesCreateResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\LanXinPlusOpenAPI\Model\V1MessagesCreateResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LanXinPlusOpenAPI\Model\V1MessagesCreateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1MessagesCreateAsync
     *
     * 发送应用消息应用号通道
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V1MessagesCreateRequestBody $v1_messages_create_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1MessagesCreateAsync($app_token, $v1_messages_create_request_body, $user_token = null)
    {
        return $this->v1MessagesCreateAsyncWithHttpInfo($app_token, $v1_messages_create_request_body, $user_token)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1MessagesCreateAsyncWithHttpInfo
     *
     * 发送应用消息应用号通道
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V1MessagesCreateRequestBody $v1_messages_create_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1MessagesCreateAsyncWithHttpInfo($app_token, $v1_messages_create_request_body, $user_token = null)
    {
        $returnType = '\LanXinPlusOpenAPI\Model\V1MessagesCreateResponse';
        $request = $this->v1MessagesCreateRequest($app_token, $v1_messages_create_request_body, $user_token);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1MessagesCreate'
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V1MessagesCreateRequestBody $v1_messages_create_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1MessagesCreateRequest($app_token, $v1_messages_create_request_body, $user_token = null)
    {
        // verify the required parameter 'app_token' is set
        if ($app_token === null || (is_array($app_token) && count($app_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app_token when calling v1MessagesCreate'
            );
        }
        // verify the required parameter 'v1_messages_create_request_body' is set
        if ($v1_messages_create_request_body === null || (is_array($v1_messages_create_request_body) && count($v1_messages_create_request_body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $v1_messages_create_request_body when calling v1MessagesCreate'
            );
        }

        $resourcePath = '/v1/messages/create';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($app_token !== null) {
            if('form' === 'form' && is_array($app_token)) {
                foreach($app_token as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['app_token'] = $app_token;
            }
        }
        // query params
        if ($user_token !== null) {
            if('form' === 'form' && is_array($user_token)) {
                foreach($user_token as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['user_token'] = $user_token;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($v1_messages_create_request_body)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($v1_messages_create_request_body));
            } else {
                $httpBody = $v1_messages_create_request_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1MessagesNotificationCreate
     *
     * 发送通知消息
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V1MessagesNotificationCreateRequestBody $v1_messages_notification_create_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \LanXinPlusOpenAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \LanXinPlusOpenAPI\Model\V1MessagesNotificationCreateResponse
     */
    public function v1MessagesNotificationCreate($app_token, $v1_messages_notification_create_request_body, $user_token = null)
    {
        list($response) = $this->v1MessagesNotificationCreateWithHttpInfo($app_token, $v1_messages_notification_create_request_body, $user_token);
        return $response;
    }

    /**
     * Operation v1MessagesNotificationCreateWithHttpInfo
     *
     * 发送通知消息
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V1MessagesNotificationCreateRequestBody $v1_messages_notification_create_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \LanXinPlusOpenAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \LanXinPlusOpenAPI\Model\V1MessagesNotificationCreateResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1MessagesNotificationCreateWithHttpInfo($app_token, $v1_messages_notification_create_request_body, $user_token = null)
    {
        $request = $this->v1MessagesNotificationCreateRequest($app_token, $v1_messages_notification_create_request_body, $user_token);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\LanXinPlusOpenAPI\Model\V1MessagesNotificationCreateResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LanXinPlusOpenAPI\Model\V1MessagesNotificationCreateResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\LanXinPlusOpenAPI\Model\V1MessagesNotificationCreateResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LanXinPlusOpenAPI\Model\V1MessagesNotificationCreateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1MessagesNotificationCreateAsync
     *
     * 发送通知消息
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V1MessagesNotificationCreateRequestBody $v1_messages_notification_create_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1MessagesNotificationCreateAsync($app_token, $v1_messages_notification_create_request_body, $user_token = null)
    {
        return $this->v1MessagesNotificationCreateAsyncWithHttpInfo($app_token, $v1_messages_notification_create_request_body, $user_token)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1MessagesNotificationCreateAsyncWithHttpInfo
     *
     * 发送通知消息
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V1MessagesNotificationCreateRequestBody $v1_messages_notification_create_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1MessagesNotificationCreateAsyncWithHttpInfo($app_token, $v1_messages_notification_create_request_body, $user_token = null)
    {
        $returnType = '\LanXinPlusOpenAPI\Model\V1MessagesNotificationCreateResponse';
        $request = $this->v1MessagesNotificationCreateRequest($app_token, $v1_messages_notification_create_request_body, $user_token);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1MessagesNotificationCreate'
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V1MessagesNotificationCreateRequestBody $v1_messages_notification_create_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1MessagesNotificationCreateRequest($app_token, $v1_messages_notification_create_request_body, $user_token = null)
    {
        // verify the required parameter 'app_token' is set
        if ($app_token === null || (is_array($app_token) && count($app_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app_token when calling v1MessagesNotificationCreate'
            );
        }
        // verify the required parameter 'v1_messages_notification_create_request_body' is set
        if ($v1_messages_notification_create_request_body === null || (is_array($v1_messages_notification_create_request_body) && count($v1_messages_notification_create_request_body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $v1_messages_notification_create_request_body when calling v1MessagesNotificationCreate'
            );
        }

        $resourcePath = '/v1/messages/notification/create';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($app_token !== null) {
            if('form' === 'form' && is_array($app_token)) {
                foreach($app_token as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['app_token'] = $app_token;
            }
        }
        // query params
        if ($user_token !== null) {
            if('form' === 'form' && is_array($user_token)) {
                foreach($user_token as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['user_token'] = $user_token;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($v1_messages_notification_create_request_body)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($v1_messages_notification_create_request_body));
            } else {
                $httpBody = $v1_messages_notification_create_request_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1MessagesRevoke
     *
     * 撤回消息
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V1MessagesRevokeRequestBody $v1_messages_revoke_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \LanXinPlusOpenAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \LanXinPlusOpenAPI\Model\V1MessagesRevokeResponse
     */
    public function v1MessagesRevoke($app_token, $v1_messages_revoke_request_body, $user_token = null)
    {
        list($response) = $this->v1MessagesRevokeWithHttpInfo($app_token, $v1_messages_revoke_request_body, $user_token);
        return $response;
    }

    /**
     * Operation v1MessagesRevokeWithHttpInfo
     *
     * 撤回消息
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V1MessagesRevokeRequestBody $v1_messages_revoke_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \LanXinPlusOpenAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \LanXinPlusOpenAPI\Model\V1MessagesRevokeResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1MessagesRevokeWithHttpInfo($app_token, $v1_messages_revoke_request_body, $user_token = null)
    {
        $request = $this->v1MessagesRevokeRequest($app_token, $v1_messages_revoke_request_body, $user_token);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\LanXinPlusOpenAPI\Model\V1MessagesRevokeResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LanXinPlusOpenAPI\Model\V1MessagesRevokeResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\LanXinPlusOpenAPI\Model\V1MessagesRevokeResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LanXinPlusOpenAPI\Model\V1MessagesRevokeResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1MessagesRevokeAsync
     *
     * 撤回消息
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V1MessagesRevokeRequestBody $v1_messages_revoke_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1MessagesRevokeAsync($app_token, $v1_messages_revoke_request_body, $user_token = null)
    {
        return $this->v1MessagesRevokeAsyncWithHttpInfo($app_token, $v1_messages_revoke_request_body, $user_token)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1MessagesRevokeAsyncWithHttpInfo
     *
     * 撤回消息
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V1MessagesRevokeRequestBody $v1_messages_revoke_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1MessagesRevokeAsyncWithHttpInfo($app_token, $v1_messages_revoke_request_body, $user_token = null)
    {
        $returnType = '\LanXinPlusOpenAPI\Model\V1MessagesRevokeResponse';
        $request = $this->v1MessagesRevokeRequest($app_token, $v1_messages_revoke_request_body, $user_token);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1MessagesRevoke'
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V1MessagesRevokeRequestBody $v1_messages_revoke_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1MessagesRevokeRequest($app_token, $v1_messages_revoke_request_body, $user_token = null)
    {
        // verify the required parameter 'app_token' is set
        if ($app_token === null || (is_array($app_token) && count($app_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app_token when calling v1MessagesRevoke'
            );
        }
        // verify the required parameter 'v1_messages_revoke_request_body' is set
        if ($v1_messages_revoke_request_body === null || (is_array($v1_messages_revoke_request_body) && count($v1_messages_revoke_request_body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $v1_messages_revoke_request_body when calling v1MessagesRevoke'
            );
        }

        $resourcePath = '/v1/messages/revoke';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($app_token !== null) {
            if('form' === 'form' && is_array($app_token)) {
                foreach($app_token as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['app_token'] = $app_token;
            }
        }
        // query params
        if ($user_token !== null) {
            if('form' === 'form' && is_array($user_token)) {
                foreach($user_token as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['user_token'] = $user_token;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($v1_messages_revoke_request_body)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($v1_messages_revoke_request_body));
            } else {
                $httpBody = $v1_messages_revoke_request_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v2ChatNotificationUpdate
     *
     * 更新通知消息会话状态（批量）
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V2ChatNotificationUpdateRequestBody $v2_chat_notification_update_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \LanXinPlusOpenAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \LanXinPlusOpenAPI\Model\V2ChatNotificationUpdateResponse
     */
    public function v2ChatNotificationUpdate($app_token, $v2_chat_notification_update_request_body, $user_token = null)
    {
        list($response) = $this->v2ChatNotificationUpdateWithHttpInfo($app_token, $v2_chat_notification_update_request_body, $user_token);
        return $response;
    }

    /**
     * Operation v2ChatNotificationUpdateWithHttpInfo
     *
     * 更新通知消息会话状态（批量）
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V2ChatNotificationUpdateRequestBody $v2_chat_notification_update_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \LanXinPlusOpenAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \LanXinPlusOpenAPI\Model\V2ChatNotificationUpdateResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function v2ChatNotificationUpdateWithHttpInfo($app_token, $v2_chat_notification_update_request_body, $user_token = null)
    {
        $request = $this->v2ChatNotificationUpdateRequest($app_token, $v2_chat_notification_update_request_body, $user_token);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\LanXinPlusOpenAPI\Model\V2ChatNotificationUpdateResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LanXinPlusOpenAPI\Model\V2ChatNotificationUpdateResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\LanXinPlusOpenAPI\Model\V2ChatNotificationUpdateResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LanXinPlusOpenAPI\Model\V2ChatNotificationUpdateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v2ChatNotificationUpdateAsync
     *
     * 更新通知消息会话状态（批量）
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V2ChatNotificationUpdateRequestBody $v2_chat_notification_update_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v2ChatNotificationUpdateAsync($app_token, $v2_chat_notification_update_request_body, $user_token = null)
    {
        return $this->v2ChatNotificationUpdateAsyncWithHttpInfo($app_token, $v2_chat_notification_update_request_body, $user_token)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v2ChatNotificationUpdateAsyncWithHttpInfo
     *
     * 更新通知消息会话状态（批量）
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V2ChatNotificationUpdateRequestBody $v2_chat_notification_update_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v2ChatNotificationUpdateAsyncWithHttpInfo($app_token, $v2_chat_notification_update_request_body, $user_token = null)
    {
        $returnType = '\LanXinPlusOpenAPI\Model\V2ChatNotificationUpdateResponse';
        $request = $this->v2ChatNotificationUpdateRequest($app_token, $v2_chat_notification_update_request_body, $user_token);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v2ChatNotificationUpdate'
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V2ChatNotificationUpdateRequestBody $v2_chat_notification_update_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v2ChatNotificationUpdateRequest($app_token, $v2_chat_notification_update_request_body, $user_token = null)
    {
        // verify the required parameter 'app_token' is set
        if ($app_token === null || (is_array($app_token) && count($app_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app_token when calling v2ChatNotificationUpdate'
            );
        }
        // verify the required parameter 'v2_chat_notification_update_request_body' is set
        if ($v2_chat_notification_update_request_body === null || (is_array($v2_chat_notification_update_request_body) && count($v2_chat_notification_update_request_body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $v2_chat_notification_update_request_body when calling v2ChatNotificationUpdate'
            );
        }

        $resourcePath = '/v2/chat/notification/update';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($app_token !== null) {
            if('form' === 'form' && is_array($app_token)) {
                foreach($app_token as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['app_token'] = $app_token;
            }
        }
        // query params
        if ($user_token !== null) {
            if('form' === 'form' && is_array($user_token)) {
                foreach($user_token as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['user_token'] = $user_token;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($v2_chat_notification_update_request_body)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($v2_chat_notification_update_request_body));
            } else {
                $httpBody = $v2_chat_notification_update_request_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v2EventNotificationCreate
     *
     * 发送应用消息应用号通道
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V2EventNotificationCreateRequestBody $v2_event_notification_create_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \LanXinPlusOpenAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \LanXinPlusOpenAPI\Model\V2EventNotificationCreateResponse
     */
    public function v2EventNotificationCreate($app_token, $v2_event_notification_create_request_body, $user_token = null)
    {
        list($response) = $this->v2EventNotificationCreateWithHttpInfo($app_token, $v2_event_notification_create_request_body, $user_token);
        return $response;
    }

    /**
     * Operation v2EventNotificationCreateWithHttpInfo
     *
     * 发送应用消息应用号通道
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V2EventNotificationCreateRequestBody $v2_event_notification_create_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \LanXinPlusOpenAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \LanXinPlusOpenAPI\Model\V2EventNotificationCreateResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function v2EventNotificationCreateWithHttpInfo($app_token, $v2_event_notification_create_request_body, $user_token = null)
    {
        $request = $this->v2EventNotificationCreateRequest($app_token, $v2_event_notification_create_request_body, $user_token);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\LanXinPlusOpenAPI\Model\V2EventNotificationCreateResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LanXinPlusOpenAPI\Model\V2EventNotificationCreateResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\LanXinPlusOpenAPI\Model\V2EventNotificationCreateResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LanXinPlusOpenAPI\Model\V2EventNotificationCreateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v2EventNotificationCreateAsync
     *
     * 发送应用消息应用号通道
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V2EventNotificationCreateRequestBody $v2_event_notification_create_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v2EventNotificationCreateAsync($app_token, $v2_event_notification_create_request_body, $user_token = null)
    {
        return $this->v2EventNotificationCreateAsyncWithHttpInfo($app_token, $v2_event_notification_create_request_body, $user_token)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v2EventNotificationCreateAsyncWithHttpInfo
     *
     * 发送应用消息应用号通道
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V2EventNotificationCreateRequestBody $v2_event_notification_create_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v2EventNotificationCreateAsyncWithHttpInfo($app_token, $v2_event_notification_create_request_body, $user_token = null)
    {
        $returnType = '\LanXinPlusOpenAPI\Model\V2EventNotificationCreateResponse';
        $request = $this->v2EventNotificationCreateRequest($app_token, $v2_event_notification_create_request_body, $user_token);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v2EventNotificationCreate'
     *
     * @param  string $app_token app_token (required)
     * @param  \LanXinPlusOpenAPI\Model\V2EventNotificationCreateRequestBody $v2_event_notification_create_request_body Request Body (required)
     * @param  string $user_token user_token (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v2EventNotificationCreateRequest($app_token, $v2_event_notification_create_request_body, $user_token = null)
    {
        // verify the required parameter 'app_token' is set
        if ($app_token === null || (is_array($app_token) && count($app_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app_token when calling v2EventNotificationCreate'
            );
        }
        // verify the required parameter 'v2_event_notification_create_request_body' is set
        if ($v2_event_notification_create_request_body === null || (is_array($v2_event_notification_create_request_body) && count($v2_event_notification_create_request_body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $v2_event_notification_create_request_body when calling v2EventNotificationCreate'
            );
        }

        $resourcePath = '/v2/event/notification/create';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($app_token !== null) {
            if('form' === 'form' && is_array($app_token)) {
                foreach($app_token as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['app_token'] = $app_token;
            }
        }
        // query params
        if ($user_token !== null) {
            if('form' === 'form' && is_array($user_token)) {
                foreach($user_token as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['user_token'] = $user_token;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($v2_event_notification_create_request_body)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($v2_event_notification_create_request_body));
            } else {
                $httpBody = $v2_event_notification_create_request_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
