<?php
/**
 * V1UsersFetchData
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  LanXinPlusOpenAPI
 * @author   LanXin OPEN
 * @link     https://openapi.lanxin.cn
 */

/**
 * LanXin+ OpenAPI
 *
 * LanXin+ OpenAPI Platform
 *
 * Generated by: https://openapi.lanxin.cn
 */

/**
 * NOTE: This class is auto generated by LanXin+(https://openapi.lanxin.cn).
 * https://openapi.lanxin.cn
 * Do not edit the class manually.
 */

namespace LanXinPlusOpenAPI\Model;

use \ArrayAccess;
use \LanXinPlusOpenAPI\ObjectSerializer;

/**
 * V1UsersFetchData Class Doc Comment
 *
 * @category Class
 * @package  LanXinPlusOpenAPI
 * @author   LanXin+ team
 * @link     https://openapi.lanxin.cn
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class V1UsersFetchData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'V1UsersFetchData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'avatarId' => 'string',
        'avatarUrl' => 'string',
        'department' => '\LanXinPlusOpenAPI\Model\Department[]',
        'email' => 'string',
        'employeeNumber' => 'string',
        'externalId' => 'string',
        'loginName' => 'string',
        'mobilePhone' => '\LanXinPlusOpenAPI\Model\MobilePhone',
        'name' => 'string',
        'orgId' => 'string',
        'orgName' => 'string',
        'staffId' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'avatarId' => null,
        'avatarUrl' => null,
        'department' => null,
        'email' => null,
        'employeeNumber' => null,
        'externalId' => null,
        'loginName' => null,
        'mobilePhone' => null,
        'name' => null,
        'orgId' => null,
        'orgName' => null,
        'staffId' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'avatarId' => 'avatarId',
        'avatarUrl' => 'avatarUrl',
        'department' => 'department',
        'email' => 'email',
        'employeeNumber' => 'employeeNumber',
        'externalId' => 'externalId',
        'loginName' => 'loginName',
        'mobilePhone' => 'mobilePhone',
        'name' => 'name',
        'orgId' => 'orgId',
        'orgName' => 'orgName',
        'staffId' => 'staffId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'avatarId' => 'setAvatarId',
        'avatarUrl' => 'setAvatarUrl',
        'department' => 'setDepartment',
        'email' => 'setEmail',
        'employeeNumber' => 'setEmployeeNumber',
        'externalId' => 'setExternalId',
        'loginName' => 'setLoginName',
        'mobilePhone' => 'setMobilePhone',
        'name' => 'setName',
        'orgId' => 'setOrgId',
        'orgName' => 'setOrgName',
        'staffId' => 'setStaffId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'avatarId' => 'getAvatarId',
        'avatarUrl' => 'getAvatarUrl',
        'department' => 'getDepartment',
        'email' => 'getEmail',
        'employeeNumber' => 'getEmployeeNumber',
        'externalId' => 'getExternalId',
        'loginName' => 'getLoginName',
        'mobilePhone' => 'getMobilePhone',
        'name' => 'getName',
        'orgId' => 'getOrgId',
        'orgName' => 'getOrgName',
        'staffId' => 'getStaffId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['avatarId'] = $data['avatarId'] ?? null;
        $this->container['avatarUrl'] = $data['avatarUrl'] ?? null;
        $this->container['department'] = $data['department'] ?? null;
        $this->container['email'] = $data['email'] ?? null;
        $this->container['employeeNumber'] = $data['employeeNumber'] ?? null;
        $this->container['externalId'] = $data['externalId'] ?? null;
        $this->container['loginName'] = $data['loginName'] ?? null;
        $this->container['mobilePhone'] = $data['mobilePhone'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['orgId'] = $data['orgId'] ?? null;
        $this->container['orgName'] = $data['orgName'] ?? null;
        $this->container['staffId'] = $data['staffId'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets avatarId
     *
     * @return string|null
     */
    public function getAvatarId()
    {
        return $this->container['avatarId'];
    }

    /**
     * Sets avatarId
     *
     * @param string|null $avatarId 头像ID
     *
     * @return self
     */
    public function setAvatarId($avatarId)
    {
        $this->container['avatarId'] = $avatarId;

        return $this;
    }

    /**
     * Gets avatarUrl
     *
     * @return string|null
     */
    public function getAvatarUrl()
    {
        return $this->container['avatarUrl'];
    }

    /**
     * Sets avatarUrl
     *
     * @param string|null $avatarUrl 头像地址
     *
     * @return self
     */
    public function setAvatarUrl($avatarUrl)
    {
        $this->container['avatarUrl'] = $avatarUrl;

        return $this;
    }

    /**
     * Gets department
     *
     * @return \LanXinPlusOpenAPI\Model\Department[]|null
     */
    public function getDepartment()
    {
        return $this->container['department'];
    }

    /**
     * Sets department
     *
     * @param \LanXinPlusOpenAPI\Model\Department[]|null $department 部门信息
     *
     * @return self
     */
    public function setDepartment($department)
    {
        $this->container['department'] = $department;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email 邮箱地址
     *
     * @return self
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets employeeNumber
     *
     * @return string|null
     */
    public function getEmployeeNumber()
    {
        return $this->container['employeeNumber'];
    }

    /**
     * Sets employeeNumber
     *
     * @param string|null $employeeNumber 员工号
     *
     * @return self
     */
    public function setEmployeeNumber($employeeNumber)
    {
        $this->container['employeeNumber'] = $employeeNumber;

        return $this;
    }

    /**
     * Gets externalId
     *
     * @return string|null
     */
    public function getExternalId()
    {
        return $this->container['externalId'];
    }

    /**
     * Sets externalId
     *
     * @param string|null $externalId 外部数据源人员唯一ID
     *
     * @return self
     */
    public function setExternalId($externalId)
    {
        $this->container['externalId'] = $externalId;

        return $this;
    }

    /**
     * Gets loginName
     *
     * @return string|null
     */
    public function getLoginName()
    {
        return $this->container['loginName'];
    }

    /**
     * Sets loginName
     *
     * @param string|null $loginName 登录用户名
     *
     * @return self
     */
    public function setLoginName($loginName)
    {
        $this->container['loginName'] = $loginName;

        return $this;
    }

    /**
     * Gets mobilePhone
     *
     * @return \LanXinPlusOpenAPI\Model\MobilePhone|null
     */
    public function getMobilePhone()
    {
        return $this->container['mobilePhone'];
    }

    /**
     * Sets mobilePhone
     *
     * @param \LanXinPlusOpenAPI\Model\MobilePhone|null $mobilePhone mobilePhone
     *
     * @return self
     */
    public function setMobilePhone($mobilePhone)
    {
        $this->container['mobilePhone'] = $mobilePhone;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name 人员名称
     *
     * @return self
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets orgId
     *
     * @return string|null
     */
    public function getOrgId()
    {
        return $this->container['orgId'];
    }

    /**
     * Sets orgId
     *
     * @param string|null $orgId 组织ID
     *
     * @return self
     */
    public function setOrgId($orgId)
    {
        $this->container['orgId'] = $orgId;

        return $this;
    }

    /**
     * Gets orgName
     *
     * @return string|null
     */
    public function getOrgName()
    {
        return $this->container['orgName'];
    }

    /**
     * Sets orgName
     *
     * @param string|null $orgName 组织名称
     *
     * @return self
     */
    public function setOrgName($orgName)
    {
        $this->container['orgName'] = $orgName;

        return $this;
    }

    /**
     * Gets staffId
     *
     * @return string|null
     */
    public function getStaffId()
    {
        return $this->container['staffId'];
    }

    /**
     * Sets staffId
     *
     * @param string|null $staffId 人员ID
     *
     * @return self
     */
    public function setStaffId($staffId)
    {
        $this->container['staffId'] = $staffId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


