<?php
/**
 * RoleApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  LanXinPlusOpenAPI
 * @author   LanXin OPEN
 * @link     https://openapi.lanxin.cn
 */

/**
 * LanXin+ OpenAPI
 *
 * LanXin+ OpenAPI Platform
 *
 * Generated by: https://openapi.lanxin.cn
 */



namespace LanXinPlusOpenAPI\Test\Api;

use PHPUnit\Framework\TestCase;
use \GuzzleHttp\Client;
use \LanXinPlusOpenAPI\Configuration;
use \LanXinPlusOpenAPI\ApiException;
use \LanXinPlusOpenAPI\ObjectSerializer;
use \LanXinPlusOpenAPI\Api\RoleApi;
use \LanXinPlusOpenAPI\Api\AuthApi;


/**
 * RoleApiTest Class Doc Comment
 *
 * @category Class
 * @package  LanXinPlusOpenAPI
 * @author   LanXin OPEN
 * @link     https://openapi.lanxin.cn
 */
class RoleApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    protected static $config;
    public static function setUpBeforeClass(): void
    {
        // 蓝信开放平台网关地址, e.g.: https://example.com/open/apigw
        $host = "host";
        // 应用ID, e.g.: 1234567-7654321
        $appId = "appId";
        // 应用密钥, e.g.: D25F65E65D887AEFD9C92B00310286FA
        $appSecret = "appSecret";

        $config = new Configuration($host, $appId, $appSecret);
        $api = new AuthApi(new Client(), $config);
        $resp = $api->V1ApptokenCreate("client_credential" ,$appId, $appSecret);
        if ($resp->getErrCode() !=0) {
            echo "err in get appToken, errCode:", $resp->getErrCode(), ", errMsg:", $resp->getErrMsg(), PHP_EOL;
        }else{
            $config->setAppToken($resp->getData()->getAppToken());
            self::$config = $config;
        };
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for v1OrgRoleCreate
     *
     * 创建角色.
     *
     */
    public function testV1OrgRoleCreate()
    {
        $api = new RoleApi(new Client(),self::$config);
        $app_token = self::$config->getAppToken(); // string | app_token 
        $orgid = 'orgid_example'; // string | orgid 
        $v1_org_role_create_request_body = new \LanXinPlusOpenAPI\Model\V1OrgRoleCreateRequestBody(); // \LanXinPlusOpenAPI\Model\V1OrgRoleCreateRequestBody | Request Body 
        $user_token = self::$config->getUserToken(); // string | user_token (可选参数)
        try{
            $resp = $api->v1OrgRoleCreate($app_token, $orgid, $v1_org_role_create_request_body);
            print_r($resp);
            $this->assertEquals($resp->getErrCode(), 0);
        } catch (Exception $e) {
            echo 'Exception when calling RoleApi->v1OrgRoleCreate: ', $e->getMessage(), PHP_EOL;
        }
    }

    /**
     * Test case for v1OrgRoleMembersFetch
     *
     * 获取应用运营者列表.
     *
     */
    public function testV1OrgRoleMembersFetch()
    {
        $api = new RoleApi(new Client(),self::$config);
        $app_token = self::$config->getAppToken(); // string | app_token 
        $orgid = 'orgid_example'; // string | orgid 
        $roleid = 'roleid_example'; // string | roleid 
        $user_token = self::$config->getUserToken(); // string | user_token (可选参数)
        try{
            $resp = $api->v1OrgRoleMembersFetch($app_token, $orgid, $roleid);
            print_r($resp);
            $this->assertEquals($resp->getErrCode(), 0);
        } catch (Exception $e) {
            echo 'Exception when calling RoleApi->v1OrgRoleMembersFetch: ', $e->getMessage(), PHP_EOL;
        }
    }

    /**
     * Test case for v1RoleMemberCreate
     *
     * 添加角色成员.
     *
     */
    public function testV1RoleMemberCreate()
    {
        $api = new RoleApi(new Client(),self::$config);
        $app_token = self::$config->getAppToken(); // string | app_token 
        $v1_role_member_create_request_body = new \LanXinPlusOpenAPI\Model\V1RoleMemberCreateRequestBody(); // \LanXinPlusOpenAPI\Model\V1RoleMemberCreateRequestBody | Request Body 
        $user_token = self::$config->getUserToken(); // string | user_token (可选参数)
        try{
            $resp = $api->v1RoleMemberCreate($app_token, $v1_role_member_create_request_body);
            print_r($resp);
            $this->assertEquals($resp->getErrCode(), 0);
        } catch (Exception $e) {
            echo 'Exception when calling RoleApi->v1RoleMemberCreate: ', $e->getMessage(), PHP_EOL;
        }
    }

    /**
     * Test case for v1RoleMemberDelete
     *
     * 删除角色成员.
     *
     */
    public function testV1RoleMemberDelete()
    {
        $api = new RoleApi(new Client(),self::$config);
        $app_token = self::$config->getAppToken(); // string | app_token 
        $rolememberid = 'rolememberid_example'; // string | rolememberid 
        $v1_role_member_delete_request_body = new \LanXinPlusOpenAPI\Model\V1RoleMemberDeleteRequestBody(); // \LanXinPlusOpenAPI\Model\V1RoleMemberDeleteRequestBody | Request Body 
        $user_token = self::$config->getUserToken(); // string | user_token (可选参数)
        try{
            $resp = $api->v1RoleMemberDelete($app_token, $rolememberid, $v1_role_member_delete_request_body);
            print_r($resp);
            $this->assertEquals($resp->getErrCode(), 0);
        } catch (Exception $e) {
            echo 'Exception when calling RoleApi->v1RoleMemberDelete: ', $e->getMessage(), PHP_EOL;
        }
    }
}
